[package]
name = "looplace-api"
version = "0.1.7"
edition = "2021"
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "api"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
