[package]
name = "web"
version = "0.1.3"
edition = "2021"
authors.workspace = true
license.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server"]
